<a href="https://colab.research.google.com/github/arqMedes/jupyter/blob/master/analiseNodal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Número de ramos 
r = 9
#Número de nós 
n = 4 - 1  # Um nó é o de referência

print('Analise Nodal\n [Y][V] = [Ino]')

# ---------------MATRIZ ADMITÂNCIAS DE BARRA-----------------------------
Y = np.zeros((n,n)) # Array
#Auto-Admitâncias
Y[0, 0] = 1./5 + 1./2 + 1./5
Y[1, 1] = 1./10 + 1./4 + 1./5
Y[2, 2] = 1./5 + 1./2 + 1./10 + 1./2

#Admitâncias de transferências
Y[0, 1] = Y[1, 0] = -1./5 # nó 1 e nó 2
Y[0, 2] = Y[2, 0] = -1./2 - 1./5# nó 1 e nó 3
Y[2, 1] = Y[1,2] = -1./10

Y = np.matrix(Y) # matriz
print('Y = \n', Y)

# ---------------MATRIZ FONTE DE CORRENTES DE BARRA (RESULTANTE)----------------
Ino = np.zeros((n,1)) # VETOR (MATRIZ COLUNA)
Ino[0, 0] = 1 + 2
Ino[1, 0] = 3 - 2
Ino[2, 0] = -1

Ino = np.matrix(Ino)
print('Ino = \n', Ino)

#Inversa de Y é a Zbarra
Zbarra = Y.I

print('Zbarra = \n', Zbarra)

# Tensões Nodal
V = Zbarra*Ino
print('V = \n', V)

Analise Nodal
 [Y][V] = [Ino]
Y = 
 [[ 0.9  -0.2  -0.7 ]
 [-0.2   0.55 -0.1 ]
 [-0.7  -0.1   1.3 ]]
Ino = 
 [[ 3.]
 [ 1.]
 [-1.]]
Zbarra = 
 [[2.47368421 1.15789474 1.42105263]
 [1.15789474 2.38596491 0.80701754]
 [1.42105263 0.80701754 1.59649123]]
V = 
 [[7.15789474]
 [5.05263158]
 [3.47368421]]


#1ª Lei de Kirchoff

AI = 0



$$
    \begin{cases}
    nó \hspace{2mm}  A: -i_1 + I_1 + I_2 -i_2 -i_3 \\
    nó \hspace{2mm} B: +i_1 -i_3 + i_5  = 0  \\
    nó \hspace{2mm} D: -i_2 + i_3 + i_4  = 0
    \end{cases}
$$
---





![alt text](https://github.com/arqMedes/imgCirc/blob/master/anNodal.png?raw=true)

In [0]:
A = np.zeros((n , r))
# ramo r1
A[0, 0] = 1
A[2, 0] = -1

# ramo r2
A[0, 1] = -1
A[2, 1] = 1

# ramo r3
A[0, 2] = 1
A[2, 2] = -1

# ramo r4
A[0, 3] = 1
A[1, 3] = -1

# ramo r5
A[0, 4] = -1
A[1, 4] = 1

# ramo r6
A[1, 5] = 1
A[2, 5] = -1

# ramo r7
A[2, 6] = 1

# ramo r8
A[1, 7] = 1

# ramo r9
A[1, 8] = -1

A

array([[ 1., -1.,  1.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  1.,  1.,  0.,  1., -1.],
       [-1.,  1., -1.,  0.,  0., -1.,  1.,  0.,  0.]])

In [0]:
G = np.zeros((r, r))
G[0, 0] = 1./5
G[1, 1] = 1.e-10
G[2, 2] = 1./2
G[3, 3] = 1./5
G[4, 4] = 1.e-10
G[5, 5] = 1./10
G[6, 6] = 1./2
G[7, 7] = 1./4
G[8, 8] = 1.e-10

Vs = np.zeros((r, 1))
Is = np.zeros((r, 1))
Is[1,0] = 1
Is[4,0] = 2
Is[8,0] = 3

Is = np.matrix(Is)
Vs = np.matrix(Vs)
G = np.matrix(G)
A = np.matrix(A)
Gbarra = A*G*A.T
Is_no = A*(G*Vs - Is)
E = Gbarra.I*Is_no
Gbarra

matrix([[ 0.9 , -0.2 , -0.7 ],
        [-0.2 ,  0.55, -0.1 ],
        [-0.7 , -0.1 ,  1.3 ]])

In [0]:
Is_no

matrix([[ 3.],
        [ 1.],
        [-1.]])

In [0]:
E

matrix([[7.15789474],
        [5.05263158],
        [3.47368421]])